/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//'
      | '//categories'
      | '//planning'
      | '//profile'
      | '//profile/info'
      | '//profile/security'
      | '//records/'
      | '//records/[id]'
      | '//records/create'
    >,
    '//': RouteRecordInfo<
      '//',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//categories': RouteRecordInfo<
      '//categories',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//planning': RouteRecordInfo<
      '//planning',
      '/planning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//profile': RouteRecordInfo<
      '//profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | '//profile/info'
      | '//profile/security'
    >,
    '//profile/info': RouteRecordInfo<
      '//profile/info',
      '/profile/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//profile/security': RouteRecordInfo<
      '//profile/security',
      '/profile/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//records/': RouteRecordInfo<
      '//records/',
      '/records',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//records/[id]': RouteRecordInfo<
      '//records/[id]',
      '/records/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//records/create': RouteRecordInfo<
      '//records/create',
      '/records/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//'
        | '//categories'
        | '//planning'
        | '//profile'
        | '//profile/info'
        | '//profile/security'
        | '//records/'
        | '//records/[id]'
        | '//records/create'
      views:
        | 'default'
    }
    'src/pages/index/index.vue': {
      routes:
        | '//'
      views:
        | never
    }
    'src/pages/index/categories.vue': {
      routes:
        | '//categories'
      views:
        | never
    }
    'src/pages/index/planning.vue': {
      routes:
        | '//planning'
      views:
        | never
    }
    'src/pages/index/profile.vue': {
      routes:
        | '//profile'
        | '//profile/info'
        | '//profile/security'
      views:
        | 'default'
    }
    'src/pages/index/profile/info.vue': {
      routes:
        | '//profile/info'
      views:
        | never
    }
    'src/pages/index/profile/security.vue': {
      routes:
        | '//profile/security'
      views:
        | never
    }
    'src/pages/index/records/index.vue': {
      routes:
        | '//records/'
      views:
        | never
    }
    'src/pages/index/records/[id].vue': {
      routes:
        | '//records/[id]'
      views:
        | never
    }
    'src/pages/index/records/create.vue': {
      routes:
        | '//records/create'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
