name: ci

permissions:
   contents: read

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main
   workflow_dispatch: {}
   merge_group: {}

jobs:
   ci:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v6
         # workaround for npm registry key change
         # ref. `pnpm@10.1.0` / `pnpm@9.15.4` cannot be installed due to key id mismatch · Issue #612 · nodejs/corepack
         # - https://github.com/nodejs/corepack/issues/612#issuecomment-2629496091
         - run: npm i -g corepack@latest && corepack enable
         - uses: actions/setup-node@v6.3.0

         - name: 📦 Install dependencies
           run: pnpm install --frozen-lockfile

         - name: 📝 Lint
           run: pnpm lint

         - name: 💪 Type check
           run: pnpm typecheck
