name: ci

permissions:
   contents: read

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main
   workflow_dispatch: {}
   merge_group: {}

jobs:
   ci:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v7
         # workaround for npm registry key change
         - run: npm i -g corepack@latest && corepack enable
         - uses: actions/setup-node@v7.0.0
           with:
              node-version-file: .nvmrc

         - name: 📦 Install dependencies
           run: pnpm install --frozen-lockfile

         - name: 📝 Lint
           run: pnpm lint

         - name: 💪 Type check
           run: pnpm typecheck
